### ISSUE TITLE
[Feature Request] assign tag to "non-openers"

### ISSUE THREAD

**Issue by looxis-renaud** [spatie/Mailcoach#35]
There's a "marketing trick" to resend the same newsletter with a modified subject and slightly modified content to those recepients, who did not open the first newsletter.
This is to drive the engagement and open rate  :-)

Then there's also a good practise (to improve your sender's reputation) to stop sending emails (unsubscribe) to recepients who haven't opened your newsletters in a given time period (depending on your sending frequency).
You also could send a special email with a special subject to those, to encourage them to re-engage with your mails, or to get removed from your recipients list, for example with a special offer.

To be able to perform these tricks or good practices it would require to be able to automatically assign tags to recepients based on opens, or non-openers,
such as: 

- assign tag "non-opener-x_days" to those who have not opened any email in the last X days

and there should be the option to delete recepients based on assigned tasks, such as:

- delete/unsubscribe all recepients with tag "non-opener-1year"

**Comment by freekmurze** [comment]
Thank you for your suggestion.

We don't have automations like this in the package because everyone needs slightly different automations. You can use the events the package emits to programmatically add tags to subscribers (a `$subscriber` has convinience methods on it to work with tags. 

The tables the mailcoach provides should be simple enough to write your own queries for.

The events are listed here: https://mailcoach.app/docs/v2/package/advanced-usage/handling-events
